version: '3.7'
services:
  webcrawler: &webcrawler
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - bundle:/bundle
      - .:/mycrawler
    env_file: .env
    command: bash -c "rm -f tmp/pids/server.pid && sleep 100000"

  postgres:
    image: postgres:12.6
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  worker:
    <<: *webcrawler
    ports: []
    command: bundle exec sidekiq -C config/sidekiq.yml

volumes:
  bundle:
  postgres:
  redis: